name: code coverage

on:
  workflow_dispatch:
    #inputs:
    #  debug_enabled:
    #    description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
    #    required: false
    #    default: false

jobs:
  cov:
    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows-latest]
        include:
        - os: windows-latest
          pio_lib_path: D:\a\Luos

    steps:
    - uses: actions/checkout@v2
    
     ## Enable tmate debugging of manually-triggered workflows if the input option was provided    
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
    #  #if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

    - name: Begin
      run: echo Go!
      
    - name: Install Perl Strawberry
      run: choco install strawberryperl

    - name: Install Golang
      run: choco install golang
      
    - name: Install lcov
      run: choco install lcov

    - name: List all disks
      run: wmic logicaldisk get caption

    #- name: C
    #  run: |
    #    C:
    #    cd\
    #    cmd /r dir perl.exe /s /b

    - name: Find notepad
      run: Get-Command notepad
      continue-on-error: true

    - name: Find Perl
      run:  Get-Command perl
      continue-on-error: true

    - name: Find Go
      run:  Get-Command go
      continue-on-error: true
            
    - name: Change directory
      run: |
        C:
        cd\

    #- name: cat log choc
    #  run: cat C:\ProgramData\chocolatey\logs\chocolatey.log
    #  continue-on-error: true

    - name: Search go
      run: cmd /r dir go.exe /s /b
      continue-on-error: true
      
    - name: Search perl
      run: cmd /r dir perl.exe /s /b
      continue-on-error: true      

    - name: Search Gcov
      run: cmd /r dir gcov.exe /s /b
      continue-on-error: true

    - name: Search Geninfo
      run: cmd /r dir geninfo.perl /s /b
      continue-on-error: true

    - name: Search Lcov
      run: cmd /r dir lcov.perl /s /b    
      continue-on-error: true
      
    - name: Search Genhtml
      run: cmd /r dir genhtml.perl /s /b 
      continue-on-error: true

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        npm install -g clang-format
      continue-on-error: true
    
    - name: Check out Luos repository
      uses: actions/checkout@v2

    - name: Create env repo
      shell: bash
      run: |
        git clone https://github.com/Luos-io/Luos.git
        cd Luos
        git checkout mem_alloc_UT
      continue-on-error: true
    
    - name: Run PlatformIO Unit tests
      env:
        PLATFORMIO_LIB_EXTRA_DIRS: ${{ matrix.pio_lib_path }}
      run: |
        cd Luos
        $curDir = Get-Location
        $env:PLATFORMIO_LIB_EXTRA_DIRS = Split-Path -Path $curDir -Parent
        echo $env:PLATFORMIO_LIB_EXTRA_DIRS        
        pwd
        platformio run -t clean;platformio test -e native -v --filter "*mem*" 
      continue-on-error: true

    - name: TU
      run: |
        cd Luos      
        mkdir .\test\CodeCoverage
        $path=split-path (Get-Command chocolatey).Path
        $command_gcov=     (Get-Command gcov.exe).Path + " .\.pio\build\native\test\memory_allocator\unit_test_mem_alloc.gcno .\.pio\build\native\test\memory_allocator_static\unit_test_mem_alloc_static.gcno .\.pio\build\native\test\memory_allocator_tx\unit_test_mem_alloc_tx.gcno"
        $command_geninfo_1= (Get-Command perl.exe).Path + " $path\..\lib\lcov\tools\bin\geninfo .\.pio\build\native\test\memory_allocator_static\ -o .\memory_allocator_static.info"
        $command_geninfo_2=(Get-Command perl.exe).Path + " $path\..\lib\lcov\tools\bin\geninfo .\.pio\build\native\test\memory_allocator\ -o .\memory_allocator.info"
        $command_geninfo_3=(Get-Command perl.exe).Path + " $path\..\lib\lcov\tools\bin\geninfo .\.pio\build\native\test\memory_allocator_tx\ -o .\memory_allocator_tx.info"
        $command_lcov=     (Get-Command perl.exe).Path + " $path\..\lib\lcov\tools\bin\lcov --add-tracefile memory_allocator.info -a memory_allocator_static.info -a memory_allocator_tx.info -o merged.info"
        $command_genhtml=  (Get-Command perl.exe).Path + " $path\..\lib\lcov\tools\bin\genhtml merged.info -o .\test\CodeCoverage"
        echo $path
        echo $command_gcov
        echo $command_geninfo_1
        echo $command_geninfo_2
        echo $command_geninfo_3
        echo $command_lcov
        echo $command_genhtml
        ls C:\ProgramData\Chocolatey\lib
        Invoke-Expression $command_gcov
        Invoke-Expression $command_geninfo_1
        Invoke-Expression $command_geninfo_2
        Invoke-Expression $command_geninfo_3
        Invoke-Expression $command_lcov
        Invoke-Expression $command_genhtml
      continue-on-error: true

    - name: Publish artifact on Readme
      run: |
        Compress-Archive -Path .\test\CodeCoverage\* -DestinationPath .\code_coverage.Zip
        ls
      continue-on-error: true

    - name: zip
      run: |
        Compress-Archive -Path .\test\CodeCoverage\* -DestinationPath .\test\code_coverage.Zip
        ls
      continue-on-error: true
