name: code coverage

on:
  workflow_dispatch:


jobs:
#------------------------------------------
  build_and_test:
  #------------------------------------------
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
        - os: windows-latest
          pio_lib_path: D:\a\Luos

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      if: ${{ runner.os == 'Windows' }}
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Set up Node
      if: ${{ runner.os == 'Windows' }}
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      if: ${{ runner.os == 'Windows' }}
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        npm install -g clang-format
      
    - name: Check out Luos repository
      uses: actions/checkout@v2

    - name: Create env repo
      shell: bash
      if: ${{ runner.os == 'Windows' }}
      run: |
        git clone https://github.com/Rakadar33/Luos.git
        cd Luos
        #git checkout mem_alloc_UT

    - name: Run PlatformIO Unit tests
      env:
        PLATFORMIO_LIB_EXTRA_DIRS: ${{ matrix.pio_lib_path }}
      if: ${{ runner.os == 'Windows' }}
      run: |
        cd Luos
        $curDir = Get-Location
        $env:PLATFORMIO_LIB_EXTRA_DIRS = Split-Path -Path $curDir -Parent
        # platformio run -t clean;platformio test -e native -v --filter "*mem*" -i CodeCoverage
        platformio run -t clean;platformio test -i CodeCoverage

    - name: Zip directory
      if: ${{ runner.os == 'Windows' }}
      run: |
        Compress-Archive -Path .\Luos\* -DestinationPath luos.Zip

    - if: ${{ runner.os == 'windows-latest' }}
      uses: actions/upload-artifact@v1
      with:
        name: result
        path: luos.Zip
   
    #- name: Create ouput coverageTag
    #  if: ${{ runner.os == 'Windows' }}
    #  run: env=
   
    #outputs:
    #  coverageTag: 'true'

        
  #------------------------------------------
  coverage:
  #------------------------------------------
    name: Code Coverage
    needs: build_and_test
    #runs-on: [windows-latest, "${{ needs.build_and_test.outputs.coverageTag }}"]
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v1
      with:
         name: result

    - name: Install Windows dependencies
      if: ${{ runner.os == 'Windows' }}
      run: |
        choco install strawberryperl
        choco install golang
        choco install lcov

    - name: Unzip artifact
      run: |
        ls
        cd ./result        
        ls
        Expand-Archive -LiteralPath luos.Zip -DestinationPath .
        ls

    - name: Coverage generation
      run: |
        # TODO : rendre indépendant du nombre de files (boucle for)
        #

        cd ./result        
        
        $directoyPath=".\test\CodeCoverage";
        if(!(Test-Path -path $directoyPath))  
        {  
            New-Item -ItemType directory -Path $directoyPath
            Write-Host "Folder path has been created successfully at: " $directoyPath
        }
                
        $path=split-path (Get-Command chocolatey).Path

        ls
        ls .\.pio\
        ls .\.pio\build\native\test\memory_allocator_tx\
        Get-ChildItem -Path . -Filter *.gcno -Recurse -ErrorAction SilentlyContinue -Force
        Get-ChildItem -Path . -Filter *.gcda -Recurse -ErrorAction SilentlyContinue -Force         
        
        # ----- $command_gcov=     (Get-Command gcov.exe).Path + " .\.pio\build\native\test\memory_allocator\unit_test_mem_alloc.gcno .\.pio\build\native\test\memory_allocator_static\unit_test_mem_alloc_static.gcno .\.pio\build\native\test\memory_allocator_tx\unit_test_mem_alloc_tx.gcno"
        $command_gcov=     (Get-Command gcov.exe).Path + " .\.pio\build\native\test\memory_allocator\unit_test_mem_alloc.gcda .\.pio\build\native\test\memory_allocator_static\unit_test_mem_alloc_static.gcda .\.pio\build\native\test\memory_allocator_tx\unit_test_mem_alloc_tx.gcda"
        $command_geninfo_1= (Get-Command perl.exe).Path + " $path\..\lib\lcov\tools\bin\geninfo .\.pio\build\native\test\memory_allocator_static\ -o .\memory_allocator_static.info"
        $command_geninfo_2=(Get-Command perl.exe).Path + " $path\..\lib\lcov\tools\bin\geninfo .\.pio\build\native\test\memory_allocator\ -o .\memory_allocator.info"
        $command_geninfo_3=(Get-Command perl.exe).Path + " $path\..\lib\lcov\tools\bin\geninfo .\.pio\build\native\test\memory_allocator_tx\ -o .\memory_allocator_tx.info"
        $command_lcov=     (Get-Command perl.exe).Path + " $path\..\lib\lcov\tools\bin\lcov --add-tracefile memory_allocator.info -a memory_allocator_static.info -a memory_allocator_tx.info -o merged.info"
        # -------- $command_genhtml=  (Get-Command perl.exe).Path + "$path\..\lib\lcov\tools\bin\genhtml merged.info -o .\test\CodeCoverage"
        $command_genhtml=  (Get-Command perl.exe).Path + " $path\..\lib\lcov\tools\bin\genhtml merged.info -o $WINDOWS_WORKSPACE\test\CodeCoverage\"
        Invoke-Expression $command_gcov
        Invoke-Expression $command_geninfo_1
        Invoke-Expression $command_geninfo_2
        Invoke-Expression $command_geninfo_3
        Invoke-Expression $command_lcov
        ls
        Invoke-Expression $command_genhtml

    #- name: zip
    #  run: Compress-Archive -Path .\test\CodeCoverage\* -DestinationPath .\test\code_coverage.Zip        

    - name: Publish artifact on Readme
      run: |
        ls
      #uses: zgosalvez/github-actions-report-lcov@49af65b0586c274a625a41a2dc8aaaae7d00568b
      #with:
      #  coverage-files: $WINDOWS_WORKSPACE\test\CodeCoverage\merged.info
      #  minimum-coverage: 3
      #  artifact-name: code-coverage-report
      #  github-token: ${{ secrets.GITHUB_TOKEN }}
