name: code coverage

on:
  workflow_dispatch:
    #inputs:
    #  debug_enabled:
    #    description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
    #    required: false
    #    default: false

jobs:
  cov:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
     ## Enable tmate debugging of manually-triggered workflows if the input option was provided    
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
    #  #if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

    - name: Begin
      run: echo Go!
      
    - name: Install Perl Strawberry
      run: choco install strawberryperl

    - name: Install Golang
      run: choco install golang

    - name: Search Gcov
      run: |
        c:
        cd\

    - name: Search Geninfo
      run: cmd /r dir geninfo.perl /s /b

    - name: Search Lcov
      run: cmd /r dir lcov.perl /s /b    

    - name: Search Genhtml
      run: genhtml
