name: code coverage

on:
  workflow_dispatch:

jobs:
  cov:
    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows-latest]
        include:
        - os: windows-latest
          pio_lib_path: D:\a\Luos

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        npm install -g clang-format
      
    - name: Install Windows dependencies
      if: ${{ runner.os == 'Windows' }}
      run: |
        choco install strawberryperl
        choco install golang
        choco install lcov
    
    - name: Check out Luos repository
      uses: actions/checkout@v2

    - name: Create env repo
      shell: bash
      run: |
        #git clone https://github.com/Luos-io/Luos.git
        git clone https://github.com/Rakadar33/Lulu.git
        cd Luos
        git checkout mem_alloc_UT
    
    - name: Run PlatformIO Unit tests
      env:
        PLATFORMIO_LIB_EXTRA_DIRS: ${{ matrix.pio_lib_path }}
      run: |
        cd Luos
        $curDir = Get-Location
        $env:PLATFORMIO_LIB_EXTRA_DIRS = Split-Path -Path $curDir -Parent
        platformio run -t clean;platformio test -e native -v --filter "*mem*" 

    - name: TU
      run: |
        # TODO : rendre indépendant du nombre de files (boucle for)
        # 
        cd Luos      
        mkdir .\test\CodeCoverage
        $path=split-path (Get-Command chocolatey).Path
        $command_gcov=     (Get-Command gcov.exe).Path + " .\.pio\build\native\test\memory_allocator\unit_test_mem_alloc.gcno .\.pio\build\native\test\memory_allocator_static\unit_test_mem_alloc_static.gcno .\.pio\build\native\test\memory_allocator_tx\unit_test_mem_alloc_tx.gcno"
        $command_geninfo_1= (Get-Command perl.exe).Path + " $path\..\lib\lcov\tools\bin\geninfo .\.pio\build\native\test\memory_allocator_static\ -o .\memory_allocator_static.info"
        $command_geninfo_2=(Get-Command perl.exe).Path + " $path\..\lib\lcov\tools\bin\geninfo .\.pio\build\native\test\memory_allocator\ -o .\memory_allocator.info"
        $command_geninfo_3=(Get-Command perl.exe).Path + " $path\..\lib\lcov\tools\bin\geninfo .\.pio\build\native\test\memory_allocator_tx\ -o .\memory_allocator_tx.info"
        $command_lcov=     (Get-Command perl.exe).Path + " $path\..\lib\lcov\tools\bin\lcov --add-tracefile memory_allocator.info -a memory_allocator_static.info -a memory_allocator_tx.info -o merged.info"
        $command_genhtml=  (Get-Command perl.exe).Path + " $path\..\lib\lcov\tools\bin\genhtml merged.info -o .\test\CodeCoverage"
        Invoke-Expression $command_gcov
        Invoke-Expression $command_geninfo_1
        Invoke-Expression $command_geninfo_2
        Invoke-Expression $command_geninfo_3
        Invoke-Expression $command_lcov
        Invoke-Expression $command_genhtml

    - name: Publish artifact on Readme
      run: |
        # TODO : Artifact + publish sur markdown readme
        # 
        ls

    - name: zip
      run: |
        Compress-Archive -Path .\test\CodeCoverage\* -DestinationPath .\test\code_coverage.Zip
