name: aaa

on:
  workflow_dispatch:

env:
  UBUNTU_WORKSPACE: '~/work/Luos'
  MACOS_WORKSPACE: '~/work/Luos'  
  WINDOWS_WORKSPACE: 'D:\a\Luos'


jobs:
  #------------------------------------------
  build_and_test:
  #------------------------------------------
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
        - os: windows-latest
          pio_lib_path: D:\a\Luos

    steps:
    - uses: actions/checkout@v2
    
    - name: echo-var
      run: |
        echo test_111
        echo "${{ env.WINDOWS_WORKSPACE }}"
        
      continue-on-error: true        

    - name: Create Workspace
      run: |
        D:
        ls        
        cd\
        cd a
        ls        
        mkdir Luos
        ls
        cd "${{ env.WINDOWS_WORKSPACE }}"        
        ls
      continue-on-error: true                

    - name: Create Workspace
      run: |
        mkdir abcd
        ls
        cd abcd        
        echo 1 > test.txt
        cat test.txt
      continue-on-error: true        

    - uses: actions/cache@v2
      id: test-results
      with:
        path: ${{ env.WINDOWS_WORKSPACE }}/*
        key: ${{ runner.os }}-${{ steps.date.outputs.date }}-result
        
  #------------------------------------------
  coverage:
  #------------------------------------------
    name: ererer
    needs: build_and_test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      id: test-results
      with:
        path: ${{ env.WINDOWS_WORKSPACE }}/*
        key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-result

    - name: st1
      run: |
        cd\
        cd ${{ env.WINDOWS_WORKSPACE }}
        ls
        cd abcd
        ls
      continue-on-error: true                

    - name: st2
      run: |
        cat test.txt
      continue-on-error: true                
