name: aaa

on:
  workflow_dispatch:

env:
  UBUNTU_WORKSPACE: '~/work/Luos'
  MACOS_WORKSPACE: '~/work/Luos'  
  WINDOWS_WORKSPACE: 'D:\a\Luos'


jobs:
  #------------------------------------------
  build_and_test:
  #------------------------------------------
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
        - os: windows-latest
          pio_lib_path: D:\a\Luos

    steps:
    - uses: actions/checkout@v2
    
    - name: echo-var
      run: |
        echo test_111
        echo "${{ env.WINDOWS_WORKSPACE }}"
        
      continue-on-error: true        

    - name: Create Workspace
      run: |
        D:
        ls        
        cd\
        cd a
        ls        
        mkdir Luos
        ls
        cd "${{ env.WINDOWS_WORKSPACE }}"        
        ls
      continue-on-error: true                

    - name: Create Workspace22
      run: |
        mkdir abcd
        ls
        cd abcd        
        echo 1 > test.txt
        cat test.txt
      continue-on-error: true    
      
    - name: Create Workspace33
      run: |
        d:
        cd D:\a\Luos
        echo 22222 > test2.txt
        mkdir azerty
        cd azerty
        echo 33333 > test3.txt        
        cat test3.txt
        mkdir new
        cd new
        echo 44444> test4.txt                
      continue-on-error: true          

    - name: zip
      run: Compress-Archive -Path D:\a\Luos\* -DestinationPath D:\a\Luos\result.zip

    - uses: actions/upload-artifact@v1
      with:
        name: result
        path: D:\a\Luos\result.zip

    #- name: Cache Modules
    #  id: test-results
    #  uses: actions/cache@v2
    #  with:
    #    path: ${{ env.WINDOWS_WORKSPACE }}/*
    #    #key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    #    #key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-result
    #    #key: node-modules-${{ hashFiles('package-lock.json') }}

    #- uses: actions/cache@v2
    #  id: test-results
    #  with:
    #    path: ${{ env.WINDOWS_WORKSPACE }}/*
    #    key: ${{ runner.os }}-${{ steps.date.outputs.date }}-result
        
  #------------------------------------------
  coverage:
  #------------------------------------------
    name: cache-restore
    needs: build_and_test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2

    #- uses: actions/cache@v2
    #  id: test-results
    #  with:
    #    path: ${{ env.WINDOWS_WORKSPACE }}/*
    #    key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-result

    - uses: actions/download-artifact@v1
      with:
        name: result
      
    - name: first
      run: |
        ls
        cd result
        ls
        Expand-Archive -LiteralPath .\result.zip -DestinationPath .
        ls
      continue-on-error: true
      
