name: Actions Workflow_2

on:
  #push:

  # exemple of schedule : every 5 & 6 minutes
  # cron help on https://crontab.guru/
  #schedule:
  #  - cron: "0/5 * * * *"
  #  - cron: "0/6 * * * *"    
  
  # Manual trigger
  # help on https://developer.github.com/v3/repos/#create-a-repository-dispatch-event
  # With a POST curl command, after creation of Tooken :
  #    curl \
  #  -X POST \
  #  -H "Accept: application/vnd.github.v3+json" \
  #  -H "Authorization: token XXX" \
  #  https://api.github.com/repos/Rakadar33/test_github_action/dispatches \
  #  -d '{\
  #  "event_type":"build_123"\
  #  "client_payload": {"env" : "production}\
  #  }'

  
  repository_dispatch:
    types: [build_123]

  pull_request:
    types: [closed, assigned, opened, reopened]
  issues:

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: get payload from curl
        run: echo "${{github.event.client_payload.env}}"
      - name: list files
        run: |
          pwd
          # ls will not print anything because our repo is not cloned 
          # to clone, we will have to use actions/checkout
          ls

          # Our commit Id SHA1 : 
          echo $GITHUB_SHA 
          # Our repo name :
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: checkout
        uses: actions/checkout@v1
      - name: list files after checkout
        run: |
          pwd
          # now with ls, we can observe our files from our repo
          ls -a
          echo just an echo to create a pull request
      - name: simple JS actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
            who-to-greet: Marcel
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time}}"
        