name: 'PR Checklist'
on: 
  pull_request:
    #types: [assigned]    
    types: [closed]    
    # TODO : to be launched by CD job
    # TODO : to be launched by CD job
    # TODO : to be launched by CD job
  workflow_dispatch:

jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - uses: venkatsarvesh/pr-tasks-completed-action@v1.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
